version: '3.8'

services:
  real-esrgan-api:
    build: .
    container_name: real-esrgan-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - OMP_NUM_THREADS=2
      - MKL_NUM_THREADS=2
    volumes:
      # Optional: mount temp directory for debugging
      - ./temp:/app/temp
    memory: 3g
    cpus: '2.0'
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import httpx; httpx.get('http://localhost:8000/health', timeout=10)"]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 60s

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: real-esrgan-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - real-esrgan-api
    restart: unless-stopped
    profiles:
      - production

networks:
  default:
    name: real-esrgan-network
